name: Deploy Backend

on:
  push:
    branches: [ master ]
    paths:
      - "backend/**"
      - ".github/workflows/production-backend.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DOKKU_HOST }} >> ~/.ssh/known_hosts

      - name: Start SSH agent and add key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Deploy Backend to Dokku
        run: |
          echo "🚀 Deploying backend application..."
          git remote add dokku-back dokku@${{ secrets.DOKKU_HOST }}:${{ secrets.DOKKU_BACK_APP_NAME }}
          git push dokku-back master

      - name: Deployment success
        run: |
          echo "✅ Backend deployment completed successfully!"
          echo "App: ${{ secrets.DOKKU_BACK_APP_NAME }}"
          if [ -n "${{ secrets.BACKEND_URL }}" ]; then
            echo "URL: ${{ secrets.BACKEND_URL }}"
          fi
